### PR TITLE
Feature bootstrap - Request to merge it to master branch

### PR DESCRIPTION
**Pull request by rsnazario**
***Thanks in advance*** 👍 

**Planning of the Project:**
 - Understand the main concept of Bootstrap
 - Master the use of bootstrap-grid (responsiveness and regular use of it)
 - Replicate the first 3 columns 
 - Apply sticky-effect
 - Mess around with these columns to fulfill any misconception 
 - replicate the other sections
 - add navbar

*Follow-map of the Project:*
- Test
- application
- reset
- test
- application
- reset 

(Most of time I was researching the documentation and videos to fully understand the main concepts of this tool, resetting the project every time I feel it would be best for me to better understand the concepts)

- Once I understood it, the project just flowed as is was originally planned.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### HI @rsnazario, you have done well. I commend your usage of bootstrap classes in this project.:+1: Here are changes required for us to move ahead:

1. Our navbar gets distorted before reaching the medium breakpoint.
image

2. The opinion section is not well aligned at certain breakpoints. You can check at 1034px and 560px screen sizes.

3. On small screen sizes, adjust the bottom margins for articles in the **"In the magazine section"** as well as **"Featured Slideshow"** section. The margins are not even and well spaced. Look at the original page.

4. You are encouraged to enclose your navbar withing `<nav>` tags.

5. Adjust your font-sizes for article titles, especially for the Top Story and Featured Story section. They are a bit too large.

6. Fix your linter errors.

_**Kindly make these changes and submit another code review request.**_

**Cheers:smile:**

### Status: Changes required.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hello @rsnazario!
You have done some really nice work! Please consider my comments below, make the necessary changes and request another review :handshake: 

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. Also, pay attention to image responsiveness. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.

##### Please pay close attention to the following sections on screen sizes from 320px up to and including 1024px, also take a thorough look at other sections incase I left something out.
screenshot
screenshot
screenshot
screenshot
screenshot
screenshot

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by rsnazario** [comment]
I found the main mistake that was causing this problems on small screens. I forgot to set one of the lists in the footer section with the class flex-wrap, so it was not respecting the 100% width and overflowing it. 

About the other views, I guided myself on every phone screen sizes and tablets size, so this is responsive through the views, right?

**Comment by rsnazario** [comment]
ps: I am not understanding what is going on with my stickler. I just added the usual way that it is supposed to but I don't get what is wrong.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**@rsnazario:clap:, your page still breaks at most of the points pointed out in the first and second review.**

Please take time to understand the required changes and fix them.

For your stickler, consider removing the files and adding them afresh. Pay attention to indentation within the files.

_**Please take care of those and submit another code review request.**_

### Status: Changes required.

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello @rsnazario ,  You have done a great job with this project. :clap: ,but fix the error below ,then go ahead with the next project.
### Page structure
- [ ] Please lets give the content padding.***Culture & Travel*** and **Signup**  sections


Status :Approved

**Pull request merged**
